### ISSUE TITLE
Error - No module named  'sugar3'

### ISSUE THREAD

**Issue by aditya113141** [sugarlabs/flappy#10]
I got the following error : -

pygame 2.0.1 (SDL 2.0.14, Python 3.6.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    from sugar3.graphics.style import GRID_CELL_SIZE
ModuleNotFoundError: No module named 'sugar3'

**Comment by quozl** [comment]
Run the activity only from within Sugar.  That will ensure the sugar3 module is available.

**Comment by aditya113141** [comment]
Is there any way to run it outside sugar?

**Comment by quozl** [comment]
I received a notification that you asked if there was any way to run it outside Sugar.  Yes, that could be done but would require changes to the source code.  You would have to make those changes.  At Sugar Labs our activity repositories are maintained primarily so that they run inside Sugar.  We don't mind accepting patches to make them run outside Sugar _as well_.  Let us know if you can do that.

**Comment by aditya113141** [comment]
![Screenshot from 2021-01-19 14-39-33](https://user-images.githubusercontent.com/56213335/105012542-440f1280-5a64-11eb-8a43-93a6d06cc2fa.png)
![Screenshot from 2021-01-19 14-39-39](https://user-images.githubusercontent.com/56213335/105012550-46716c80-5a64-11eb-8e79-55f7c0fa03aa.png)
![Screenshot from 2021-01-19 14-39-47](https://user-images.githubusercontent.com/56213335/105012559-47a29980-5a64-11eb-8700-4f48824dc8ba.png)
Is it normal for sugar activities to be displayed with other applications ( like they are shown in the pictures) on ubuntu 18.04 ?

**Comment by aditya113141** [comment]
Is it normal to see sugar icons displayed with other applications on ubuntu 18.04? I will attach the picture.

https://drive.google.com/file/d/1C0sv9XA797ssNAia9Iit52JKqH3_37yZ/view?usp=sharing

**Comment by quozl** [comment]
Yes, this is a consequence of the Toolkit creating the .desktop file.  See https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/db642e143d6bc71b9fcc8511aa6150f95fc92e63/src/sugar3/activity/bundlebuilder.py#L324 for where that is done.

Not all Sugar activities are compatible with being run outside Sugar, but as I said, we don't mind accepting patches to make them run outside Sugar.  It is not a high priority though.  The most important is to have the activities run inside Sugar, because that way the other features will work.  See https://help.sugarlabs.org/ for how Sugar is used.

**Comment by quozl** [comment]
Not a problem.
